# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/starter/server/ruby/"
    schedule:
      interval: "weekly"

  # python dependencies
  - package-ecosystem: "pip"
    directory: "/starter/server/python/"
    schedule:
      interval: "weekly"

  # php dependencies
  - package-ecosystem: "composer"
    directory: "/starter/server/php/"
    schedule:
      interval: "weekly"

  # node dependencies
  - package-ecosystem: "npm"
    directory: "/starter/server/node/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/starter/server/node-typescript/"
    schedule:
      interval: "weekly"

  # go dependencies
  - package-ecosystem: "gomod"
    directory: "/starter/server/go-echo/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/starter/server/go-http/"
    schedule:
      interval: "weekly"

  # java dependencies
  - package-ecosystem: "maven"
    directory: "/starter/server/java/"
    schedule:
      interval: "weekly"

  # dotnet dependencies
  - package-ecosystem: "nuget"
    directory: "/starter/server/dotnet/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.AspNetCore.Mvc.NewtonsoftJson"
